version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
     - API_PORT
    ports:
     - $API_PORT:$API_PORT
    networks:
     - docker-ts-nest-net
    volumes:
     - .:/api
     - /api/node_modules
    depends_on:
     - redis
  redis:
    environment:
      - REDIS_PORT
    image: redis:alpine
    expose:
      - $REDIS_PORT
    networks:
     - docker-ts-nest-net

networks:
  docker-ts-nest-net:
    driver: bridge
